name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core>=1.3
  - matplotlib>=3.5
  - pandas>=2.0
  - jupyterlab>=4.0
  - pip>=24.0
  - pip:
      - mlflow==2.16.2
      - wandb>=0.18
